#ifndef MINESWEEPERLAB_GAMEDIFFICULTY_H
#define MINESWEEPERLAB_GAMEDIFFICULTY_H

enum class GameDifficulty {
    BEGINNER = 1,
    INTERMEDIATE = 2,
    EXPERT = 3
};


#endif //MINESWEEPERLAB_GAMEDIFFICULTY_H